### PR TITLE
refs #ST-4 gitlab client implementation

### PR DESCRIPTION
**Pull request by vincenzodibiaggio**
gitlab_url:           https://gitlab.sparkfabrik.com/api/v3/

gitlab_token:      - the private token displayed here https://gitlab.sparkfabrik.com/profile/account

### CODE REVIEW

**Comment by paolomainardi** [comment]
:+1:

**Comment by paolomainardi** [comment]
@vincenzodibiaggio please write the base test class for the client.

**Comment by vincenzodibiaggio** [comment]
@paolomainardi done

**Comment by paolomainardi** [comment]
:+1:

**Pull request merged**
