### PR TITLE
refs #81: Add phpcs.xml for CS configuration

### PR DESCRIPTION
**Pull request by edodusi**
File created in project root.
Just run `phpcs` for this configuration to apply.

### CODE REVIEW

**Comment by paolomainardi** [comment]
:+1:

**Comment by paolomainardi** [comment]
Why removing also phpcbf script ?

**Comment by edodusi** [comment]
@paolomainardi because phpcbf is also getting Coding Standards informations through the `phpcs.xml` file

**Comment by paolomainardi** [comment]
Could be useful to keep it to make developers aware of that tool ?

**Comment by edodusi** [comment]
I think the tool itself should not be part of the Sparktool, because it assumes that the phpcbf executable exists on a certain path and that's not true for all users. Instead I would improve the documentation.

**Comment by paolomainardi** [comment]
@edodusi It assumes the binary because of this: https://github.com/sparkfabrik/sparktool/blob/develop/composer.json#L31

**Comment by edodusi** [comment]
Ok that's right. So what's the point of keeping binaries in `bin/` folder and scripts that actually _launch_ those binaries in `tool/` folder?

**Comment by paolomainardi** [comment]
you are right, they don't have any sense :+1:

**Comment by edodusi** [comment]
Yaeeee!! :smile:

**Pull request merged**
