### PR TITLE
refs #24 - Redmine search and order by priority

### PR DESCRIPTION
**Pull request by vincenzodibiaggio**
(sorry for issue id in the commit messages)

Not ready to merge (need tests)

At this moment order by priority work, but see the code for related changes (spark configuration, managing of output columns)

We need to talk about 'search by priority' because Redmine don't permit it :/ (priority just have an ID, not a 'weight'; maybe with a custom field with a numeric value that define the _real_ priority? 

cc @Pinolo @paolomainardi

### CODE REVIEW

**Comment by paolomainardi** [comment]
@vincenzodibiaggio the code seems to be ok, i like the refactoring for managing the output columns.

Can you write some tests ?

**Comment by vincenzodibiaggio** [comment]
ok

**Comment by vincenzodibiaggio** [comment]
updated :)

**Comment by paolomainardi** [comment]
:+1:

**Pull request merged**
