### PR TITLE
refs ST-68 - Gitlab merge request implementation with tests

### PR DESCRIPTION
**Pull request by vincenzodibiaggio**

### CODE REVIEW

**Comment by paolomainardi** [comment]
Seems that we are missing the auto build of missing configurations, this is the function who in charge of that:

```
    public function initConfig()
    {
        $this->fs = new Filesystem();
        $configFileStandardPath = $this->options['sparkHome'] . DIRECTORY_SEPARATOR . $this->options['sparkConfigFile'];
        if (!$this->fs->exists($configFileStandardPath)) {
            $this->fs->mkdir($this->options['sparkHome']);
            $defaultConfig = $this->dumpDefaultConfigurationFile();
            file_put_contents($configFileStandardPath, $defaultConfig);
        } else {
            try {
                // Merge configurations if needed.
                $dumper = new Dumper();
                $merge = array();

                // Get default config.
                $defaultConfig = Yaml::parse($this->dumpDefaultConfigurationFile());

                // Get Custom config.
                $customConfig = Yaml::parse(file_get_contents($configFileStandardPath));
                if (count($defaultConfig['spark']) !== count($customConfig['spark'])) {
                    $merge['spark'] = array_merge($defaultConfig['spark'], $customConfig['spark']);
                    $yaml_merged = $dumper->dump($merge, 5);
                    file_put_contents($configFileStandardPath, $yaml_merged);
                }
            } catch (\Exception $e) {
                die($e->getMessage() . PHP_EOL);
            }
        }
    }
```

**Comment by paolomainardi** [comment]
The basic idea is that we parse the configuration file of the user, then we parse the default configuration file described on SparkConfiguration::getConfigTreeBuilder() and try to merge them putting the missing configs on the user file.

**Comment by paolomainardi** [comment]
This is what happens now:

```
% ./spark.php gitlab:mr
PHP Notice:  Undefined index: gitlab_url in /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Services/GitlabService.php on line 42
PHP Stack trace:
PHP   1. {main}() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/spark.php:0
PHP   2. Symfony\Component\Console\Application->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/spark.php:47
PHP   3. Symfony\Component\Console\Application->doRun() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:878
PHP   6. Sparkfabrik\Tools\Spark\Command\Gitlab\GitlabMergeRequestCommand->execute() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Command/Command.php:259
PHP   7. Sparkfabrik\Tools\Spark\Command\SparkCommand->getService() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/Gitlab/GitlabMergeRequestCommand.php:84
PHP   8. Sparkfabrik\Tools\Spark\Command\Gitlab\GitlabCommand->initService() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/SparkCommand.php:35
PHP   9. Sparkfabrik\Tools\Spark\Services\AbstractService->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/Gitlab/GitlabCommand.php:49
PHP  10. Sparkfabrik\Tools\Spark\Services\GitlabService->initClient() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Services/AbstractService.php:50

Notice: Undefined index: gitlab_url in /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Services/GitlabService.php on line 42

Call Stack:
    0.0033     437904   1. {main}() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/spark.php:0
    0.0542    3802904   2. Symfony\Component\Console\Application->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/spark.php:47
    0.0560    3940544   3. Symfony\Component\Console\Application->doRun() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:126
    0.0561    3941464   4. Symfony\Component\Console\Application->doRunCommand() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:195
    0.0562    3941968   5. Symfony\Component\Console\Command\Command->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Application.php:878
    0.0566    3946472   6. Sparkfabrik\Tools\Spark\Command\Gitlab\GitlabMergeRequestCommand->execute() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/vendor/symfony/console/Command/Command.php:259
    0.0567    3946536   7. Sparkfabrik\Tools\Spark\Command\SparkCommand->getService() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/Gitlab/GitlabMergeRequestCommand.php:84
    0.0567    3946608   8. Sparkfabrik\Tools\Spark\Command\Gitlab\GitlabCommand->initService() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/SparkCommand.php:35
    0.0578    3971480   9. Sparkfabrik\Tools\Spark\Services\AbstractService->run() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Command/Gitlab/GitlabCommand.php:49
    0.0672    4070792  10. Sparkfabrik\Tools\Spark\Services\GitlabService->initClient() /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Services/AbstractService.php:50

PHP Notice:  Undefined index: gitlab_token in /Users/paolomainardi/dev/webapps/me/tools/spark-cli/src/Sparkfabrik/Services/GitlabService.php on line 44
```

And this is my configuration file:

```
% cat ~/.spark/.spark.yml
spark:
    services:
        redmine_credentials:
            redmine_url: 'https://projects.agavee.com'
            redmine_api_key: []
    projects:
        redmine_project_id: null
    git:
        branch_pattern: '%(story)_%(issue_id)_%(story_name)'
    configuration:
        redmine_output_fields: 'id|ID,project|Project,created_on|Created,updated_on|Updated,tracker|Traker,fixed_version|Version,author|Author,assigned_to|Assigned,status|Status,category|Category,estimated_hours|Estimated,subject|Subject'
```

**Comment by vincenzodibiaggio** [comment]
Done.
use id 8 for elitedom

**Comment by vincenzodibiaggio** [comment]
updated

**Pull request merged**
